sudo: required
language: go
services:
- docker
script: make -j4
deploy:
  provider: releases
  api_key:
    secure: hcXBzyseonS4wimfE7mrrNyocIsgsv+wRK/YXVdftTu9Ik2zyMowU856UbHFYtVe2UFwYz6gBGXBm37GeaaCksgzUCE8XASqy4jXc+6Pb7PatrbM/400zIp0IAUOGWzYsxmCUidegnIg/syeny83uFcPN9Vvzx3zgxHZwB9f9j4rGyZBehsjIdr6/FJiT9PJrnO1ipPK8JSPzbO1TCj14h66BDfJB0DrrdMYoB7PvRweb3g4PXsdK7cRcyW/GzJHi8/lopeCYKoVEUqPeK5REMG5FSEDVzG6KG5F2U/UoD8D7q9F7pTBO2ZAaUP45Cf6wQPrgmak0fYGKxyyDXYMa258UZPE4brR4rejQDr7KdqCXa08HaP3LHo9UgVt2+/Y+h8DBz3ycdFts39CBMVg0Cz31pvHJdtaVg3OuHAwnJckNPpYDmqXwAGGKa4+oslT6GYGxie24UcIyoc3+KlyM8032ascLANyxd3bdz2G4fKStH09g3oQxxzuSnVoyfzp+dLM2eimkEHhmDpv4LiiQ6NQtPz98Z2nTCw/4UFBFLOF0x70c1Tfr4mctp5C0ujFGOehTW4/ovo2iLwuR9jH9sUIZhiRg82ZIY6O/godjd6J+X/jp5+b66Rr+9PDY86yJixe4vtyspsa1N9X5QWWe/UKW5E2b7SwFc1kMmLJSm8=
  file:
    - "local-dns-proxy-linux-amd64"
    - "local-dns-proxy-linux-arm"
    - "local-dns-proxy-windows-amd64"
  on:
    repo: ryarnyah/local-dns-proxy
