---
name: Go build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'
      - name: Build
        run: |
          apt-get update && apt-get install -y upx
          make dev-dependencies
          make
          make cover
          make release
          find build -type f ! -name "*.md5" ! -name "*.sha256" -exec upx -9 {} \;
