---
name: Go release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build
        run: |
          make dev-dependencies
          make release
      - uses: softprops/action-gh-release@v1
        with:
          files: "build/local-dns-proxy-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
